language: generic

before_install: set -e

install:
  - export PATH="$PATH:$HOME/.local/bin"
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_success:
  - bash ci/after-success.sh

after_script: set +e

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
